//package daniel;
//
///**
// *
// * @author guida
// */
//
//public class Contador extends javax.swing.JFrame {
//
//	/**
//	 * Creates new form Contador
//	 */
//	public Contador() {
//		Fase c1 = new Fase();
//
//		initComponents(c1.getCont());
//	}
//
//	private String contador1, contador2 = "0";
//
//	/**
//	 * This method is called from within the constructor to initialize the form.
//	 * WARNING: Do NOT modify this code. The content of this method is always
//	 * regenerated by the Form Editor.
//	 */
//	@SuppressWarnings("unchecked")
//	// <editor-fold defaultstate="collapsed" desc="Generated Code">
//
//	public void initComponents(String cont) {
//		System.out.println(cont);
//		jPanel1 = new javax.swing.JPanel();
//		jPanel2 = new javax.swing.JPanel();
//		jLabel1 = new javax.swing.JLabel();
//		jLabel2 = new javax.swing.JLabel();
//
//		javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
//		jPanel1.setLayout(jPanel1Layout);
//		jPanel1Layout.setHorizontalGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
//				.addGap(0, 100, Short.MAX_VALUE));
//		jPanel1Layout.setVerticalGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
//				.addGap(0, 100, Short.MAX_VALUE));
//
//		javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
//		jPanel2.setLayout(jPanel2Layout);
//		jPanel2Layout.setHorizontalGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
//				.addGap(0, 270, Short.MAX_VALUE));
//		jPanel2Layout.setVerticalGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
//				.addGap(0, 300, Short.MAX_VALUE));
//
//		setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
//		Fase a1 = new Fase();
//		contador1 = a1.getCont();
//		System.out.println(contador1);
//		jLabel1.setText("Inimigos derrotados:" + contador1);
//		jLabel2.setText("Inimigos na cidade:" + contador2);
//
//		javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
//		getContentPane().setLayout(layout);
//		layout.setHorizontalGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
//				.addGroup(layout.createSequentialGroup().addGap(26, 26, 26)
//						.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
//								.addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE,
//										javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
//								.addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE,
//										javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
//						.addContainerGap(125, Short.MAX_VALUE)));
//		layout.setVerticalGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
//				.addGroup(layout.createSequentialGroup().addGap(43, 43, 43)
//						.addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 43,
//								javax.swing.GroupLayout.PREFERRED_SIZE)
//						.addGap(18, 18, 18).addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 43,
//								javax.swing.GroupLayout.PREFERRED_SIZE)
//						.addContainerGap(57, Short.MAX_VALUE)));
//
//		pack();
//	}// </editor-fold>
//
//	/**
//	 * @param args the command line arguments
//	 */
//
//	// Variables declaration - do not modify
//	private javax.swing.JLabel jLabel1;
//	private javax.swing.JLabel jLabel2;
//	private javax.swing.JPanel jPanel1;
//	private javax.swing.JPanel jPanel2;
//
//	// End of variables declaration
//	public class contar extends Thread {
//		String cont1, cont2;
//
//		public void run() {
//			while (true) {
//				try {
//					Contador a = new Contador();
//					a.jLabel1.setText("Inimigos derrotados:" + cont1);
//					a.jLabel2.setText("Inimigos na cidade:" + cont2);
//				} catch (Exception e) {
//				}
//			}
//		}
//	}
//}